runtime: python27 # or python
api_version: 1
threadsafe: false  # if true , handlers.script should be changed.

application: go-tex # app-id , which is applyed from google.
version: 1

handlers:
- url: /.*
  script: main.py # mainscript


libraries:  # after specify this , get "import" in the python script become possible.
- name: PIL
  version: "1.1.7"
- name: matplotlib
  version: latest
- name: numpy
  version: latest
